title: Nathan Durocher
description: Computer Vision and Machine Learning Engineer
site_title: '@ndurocher - Nathan Durocher'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ndurocher
email: nathan.durocher@gmail.com

# absolute or relative
profile_picture: docs/asstes/Owl_Logo.png

# Google Analytics ID
google_analytics: 